# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "usbhid" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f36bc0f8-22f7-47d3-b176-9fc63f1d167c";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-9b51fbef-532d-469d-a994-5bceefc04f27".device = "/dev/disk/by-uuid/9b51fbef-532d-469d-a994-5bceefc04f27";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6643-8829";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  #swapDevices =
  #  [ { device = "/dev/disk/by-uuid/91f7d6e4-5d61-426a-9631-799659546348"; }
  #  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp46s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}

